if(EXISTS "/home/alex/development/Sample_cpp/test/relaxed_constexpr_tests_tests-ff2b5b0.cmake")
  include("/home/alex/development/Sample_cpp/test/relaxed_constexpr_tests_tests-ff2b5b0.cmake")
else()
  add_test(relaxed_constexpr_tests_NOT_BUILT-ff2b5b0 relaxed_constexpr_tests_NOT_BUILT-ff2b5b0)
endif()
