if(EXISTS "/home/alex/development/Sample_cpp/test/tests_tests-4c0d252.cmake")
  include("/home/alex/development/Sample_cpp/test/tests_tests-4c0d252.cmake")
else()
  add_test(tests_NOT_BUILT-4c0d252 tests_NOT_BUILT-4c0d252)
endif()
